package sky.pro.telegrambotforpets.constants;

public enum Descriptions {

    DOG_DAITING_RULES,
    LIST_DOCUMENTS_FOR_ADOPTING,
    TRANSPORTATION_ADVICE,
    PREPARING_HOUSE_FOR_A_PUPPY,
    PREPARING_HOUSE_FOR_AN_ADULT_DOG,
    PREPARING_HOUSE_FOR_A_DISABLED_DOG,
    DOGHANDLER_ADVICIES,
    REASONS_FOR_REFUSAL
}
