-- liquibase formatted sql

-- changeset kew:1

CREATE TABLE IF NOT EXISTS shelter
(
    shelter_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shelter_name VARCHAR (40),
    shelter_adress VARCHAR(255),
    shelter_mappath VARCHAR(255),
    shelter_recomendationpath VARCHAR(255),
    shelter_schedule VARCHAR(255),
    shelter_specialization VARCHAR(255),
    shelter_description VARCHAR(255),
    shelter_security_phone_number VARCHAR(255)
);
